version: '3.1'
services:
  stats-service:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine

  main-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
